"""20210513
Create table:
- stock_basic_info
- trade_records
- users

Revision ID: 21e84b27015e
Revises: 
Create Date: 2021-05-13 10:48:10.866880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e84b27015e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False, comment='股票代號'),
    sa.Column('stock_name', sa.String(length=60), nullable=False, comment='股票名稱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='使用者名稱'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='使用者信箱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易股數'),
    sa.Column('price', sa.Integer(), nullable=False, comment='交易單價'),
    sa.Column('cost', sa.Integer(), nullable=False, comment='總成本'),
    sa.Column('activity', sa.String(length=10), nullable=False, comment='交易動作'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='創造日期'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='結束日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_records')
    op.drop_table('users')
    op.drop_table('stock_basic_info')
    # ### end Alembic commands ###
