"""20210516
Create table:
- stock_data

Revision ID: 36aa528fc44a
Revises: d3bd4b098b78
Create Date: 2021-05-16 21:51:10.321386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36aa528fc44a'
down_revision = 'd3bd4b098b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('opening_price', sa.Integer(), nullable=False, comment='開盤價'),
    sa.Column('closing_price', sa.Integer(), nullable=False, comment='收盤價'),
    sa.Column('highest_price', sa.Integer(), nullable=False, comment='最高價'),
    sa.Column('lowest_price', sa.Integer(), nullable=False, comment='最低價'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易量'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_data')
    # ### end Alembic commands ###
