"""20210517
create table:
- trade_records
- stock_data
- stock_chip
- users
- stock_basic_info

Revision ID: 4ca9dae22457
Revises: 
Create Date: 2021-05-17 15:40:59.110425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca9dae22457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False, comment='股票代號'),
    sa.Column('stock_name', sa.String(length=60), nullable=False, comment='股票名稱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='使用者名稱'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='使用者信箱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stock_chip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('net_buy_volume', sa.Integer(), nullable=False, comment='三大法人買超'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('opening_price', sa.Float(), nullable=False, comment='開盤價'),
    sa.Column('closing_price', sa.Float(), nullable=False, comment='收盤價'),
    sa.Column('highest_price', sa.Float(), nullable=False, comment='最高價'),
    sa.Column('lowest_price', sa.Float(), nullable=False, comment='最低價'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易量'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易股數'),
    sa.Column('price', sa.Integer(), nullable=False, comment='交易單價'),
    sa.Column('cost', sa.Integer(), nullable=False, comment='交易成本'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='創造日期'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_records')
    op.drop_table('stock_data')
    op.drop_table('stock_chip')
    op.drop_table('users')
    op.drop_table('stock_basic_info')
    # ### end Alembic commands ###
